#files:
#  include: './src/**/*.scss'
#  ignore:
#    - './src/components/scss/foundation-sites/**/*.*'
#    - './src/components/node_modules/**/*.*'
options:
  cache-config: false
  formatter: stylish
  merge-default-rules: true
rules:
  bem-depth:
    - 0
    - max-depth: 5
  border-zero:
    - 1
    - convention: '0'
  brace-style:
    - 1
    - style: '1tbs'
    - allow-single-line: true
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
    - allow-leading-underscore: true
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-args: true
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 5
  no-color-keyword: 0
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties:
    - 1
    - exclude:
      - display
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 0
  no-vendor-prefixes:
    - 1
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  # Alphabetical. This actually helps with gzip compression
  property-sort-order:
    - 1
    - ignore-custom-properties: false
  property-units:
    - 1
    - global:
        # - ch   # Relative to width of the "0" (zero)
        # - em   # width of the `m` character; use `rem` instead
        # - ex   # height of an `x` character; height equivalent of `em`
        - rem    # width of the `m` character of the root font
        # - cm   # centimeters
        # - in   # inches
        # - mm   # millimeters
        # - pc   # picas (1pc = 12pt)
        # - pt   # points (1pt = 1/72 of 1in)
        - px
        # - q    # quarter-millimeters, 1q = 1/40th of 1cm
        - vh     # view-height, height of view port
        - vw     # view-width, width of view port
        - vm     # ie9's version of vmin
        - vmin   # not supported by ie9
        - vmax   # not supported by ie9 or safari
        - deg
        # - grad # gradians; use `rad` instead
        - rad    # radian
        # - turn # turns; use `deg` instead
        - ms     # milliseconds
        - s      # seconds
        # - Hz   # hertz; no support
        # - kHz  # kilohertz; no support
        - dpi    # dots per inch
        # - dpcm # dots per centimeter; use dpi instead
        - dppx   # dots per px unit (1ddpx ≈ 96dpi)
        - '%'
      per-property: {
        font: ['rem'],
        font-size: ['rem']
      }
  quotes:
    - 1
    - style: 'single'
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: true
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property:
    - 1
    # @todo expand this
    - properties:
      - 'font'
      - 'font-size'
      - 'font-family'
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1