alias projects="cd ${HOME}/projects"
alias p="projects"
alias dotfiles="cd ${HOME}/projects/dotfiles"
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias github="hub"
alias gco="git checkout"
